#测试汉字
#编码为utf-8
spring:
  profiles:
    active:
      - dev
---
spring:
  application:
  profiles: dev
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: false     #\u4E0D\u4ECEeureka\u4E0A\u83B7\u53D6\u670D\u52A1\u7684\u6CE8\u518C\u4FE1\u606F
    register-with-eureka: false   #\u4E0D\u628A\u81EA\u5DF1\u6CE8\u518C\u5230eureka\u4E0A
  instance:
    hostname: eureka7001.com        #eureka\u5B9E\u4F8B\u7684\u4E3B\u673A\u540D
---
spring:
  application:
  profiles: test
server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: false     #\u4E0D\u4ECEeureka\u4E0A\u83B7\u53D6\u670D\u52A1\u7684\u6CE8\u518C\u4FE1\u606F
    register-with-eureka: false   #\u4E0D\u628A\u81EA\u5DF1\u6CE8\u518C\u5230eureka\u4E0A
  instance:
    hostname: eureka7001.com        #eureka\u5B9E\u4F8B\u7684\u4E3B\u673A\u540D